config/routes.rb
HotelMgtWithWorkflowChanged::Application.routes.draw do
  
  

  
  post  "room_books/action_gds_conf"
  
  post "room_books/add_room"
  get  "room_books/add_room"
  post  "room_books/view_rooms"
  
  
  
  post "room_books/add_room_date"
  get "room_books/add_room_date"
  post "room_books/index_with_pag"
  
  
  get "room_books/add_room_date"
  
  
  post 'room_books/get_available_room_type'
  get 'room_books/get_available_room_type'
  
  post 'room_books/add_to_gds'
  
  post 'room_books/delete_gdsline'
  
  get 'room_books/show_type/:id' => "room_books#show_type"
  post "room_books/available_for_gds" => "room_books#available_for_gds"
  post "room_books/available_for_gds/:id" => "room_books#available_for_gds"
  
  get "room_books/available_for_gds/:id" => "room_books#available_for_gds"
  get "room_books/edit_available_for_gds/:id" => "room_books#edit_available_for_gds"
  
  post "room_books/delete_allocated_room" => "room_books#delete_allocated_room"
  get "room_books/add_an_item"
  post "room_books/add_an_item"
  
  get "room_books/show_view/:id" => "room_books#show_view"
  
  get "room_books/select_shop"
  
  
  
  resources :room_books

  post "reservations/show_dates"
  get  "reservations/show_dates"
  post "reservations/show_availability_of_rooms"
  get  "reservations/room_confirm/:id" => "reservations#room_confirm"
  post  "reservations/room_confirm/" => "reservations#room_confirm"
  
  
  
  resources :reservations
  
  get "payments/get_transaction_details"
  post "payments/get_transaction_details"
  
  
  get "payments/preview_payment"
  get "payments/server_connection_error"
  post "payments/checkout"
  get "payments/confirm"
  get "payments/cancel"
  post "payments/complete"
  get "payments/rejected_payment"
  resources :payments
  
   
  
  
   
  root :to => "authenticates#select_company"
  post "authenticates/sign_in"
  get  "authenticates/sign_in"
  get  "authenticates/sign_up"
  post "authenticates/sign_up"
  post "authenticates/sign_in_auth"
  post "/authenticates/sign_up_auth"
  get "/authenticates/forgot_password"
  post "/authenticates/forgot_password_auth"
  get "/authenticates/sign_out"
  
    
  
  resources :authenticates

  
  
  
  resources :admins

  
  get "updateretes/show_rates"
  post "updateretes/show_rates"
  post "updateretes/update_rates"
  
  
  
  
  resources :updateretes

  resources :updatehoteltexts

  resources :updatebookings
  get "updateavails/all_list"
  get "updateavails/show_type/:id" => "updateavails#show_type"
  post "updateavails/available_for_gds/" => "updateavails#available_for_gds"
  post "delete_allocated_room" => "updateavails#delete_allocated_room"
  get "updateavails/get_dates" => "updateavails#get_dates"
  post "get_date_wise_available_room" => "updateavails#get_date_wise_available_room"
  post "add_to_gds" => "updateavails#add_to_gds"
  
  get "count_rooms" => "updateavails#count_rooms"
  get "update_count_rooms" => "updateavails#update_count_rooms"
  
  
  
  
  resources :updateavails

  resources :setmarkassents

  resources :setds

  resources :getroomratecodefbs

  resources :getroomratecodes

  resources :getratesdbs

  resources :getrates

  resources :getnotificationmessages

  resources :getinvoicedata

  resources :gethotels

  resources :gethotelstaticdatagds

  resources :gethotelstaticdata

  resources :getcommissionstatuses

  resources :getbookings

  resources :getavailfbs

  resources :cancelbookings

  resources :bookings

  get "savontest/index"
  
  get "gds_auth" => "gds_auths#index"
  
  get "gds_select_company" => "gds_auths#gds_select_company"
  
  get "logout" => "gds_auths#logout"
  
      
  resources :gds_auths

end

app/models/updaterete.rb
require 'net/http'
require 'xmlsimple'
class Updaterete <  ActiveRecord::Base
   
   
  
  def self.update_single_rate(params)
    
    params[:CTAMO] = 1 if params[:CTAMO].blank?
    params[:CTATU] = 1 if params[:CTATU].blank?
    params[:CTAWE] = 1 if params[:CTAWE].blank?
    params[:CTATH] = 1 if params[:CTATH].blank?
    params[:CTAFR] = 1 if params[:CTAFR].blank?
    params[:CTASA] = 1 if params[:CTASA].blank?
    params[:CTASU] = 1 if params[:CTASU].blank?
    
    #here i need to check all the checkboxes if they are blank then make it checked
    
    
        uri = URI('http://test.reconline.com/recoupdate/update.asmx/UpdateRates')
   res = Net::HTTP.post_form(uri, 'User'=> 'kedar' ,'Password'=> 'ked2012' ,
  "idHotel"=> '38534'  ,"idSystem"=>'0' ,"ForeignPropCode"=> 'blank' ,
        "IncludeRateLevels"=>'BAR' ,"ExcludeRateLevels"=> '',
        "IncludeRoomTypes"=>params[:room_type],"ExcludeRoomTypes"=>'',"RateType"=>
           '1',
        "StartDate"=> params[:begin_period],"EndDate"=>params[:end_period],"SingleOcc"=>params[:SINGLEOCCUPANCY],"DoubleOcc"=>params[:DOUBLEOCCUPANCY],
        "TripleOcc"=>params[:TRIPLEOCCUPANCY],"DoublePlusChild"=>params[:QUADRUPLEOCCUPANCY],
        "RollawayAdult"=>params[:ROLLAWAYADULT] ,"RollawayChild"=>params[:ROLLAWAYCHILD] ,"Crib"=>'0',"Meals"=>'0',
        "Advance"=> '0',"MinStay"=> '0',
        "BlockStay"=> '0',"Guarantee"=>'0',"Cancel"=>'0',"CTAMonday"=>params[:CTAMO],
        "CTATuesday"=>params[:CTATU] ,
        "CTAWednesday"=>params[:CTAWE] ,"CTAThursday"=>params[:CTATH],"CTAFriday"=>params[:CTAFR],"CTASaturday"=>params[:CTASA],
        "CTASunday"=>params[:CTASU],
        "InvalidMonday"=>'0',"InvalidTuesday"=>'0',"InvalidWednesday"=>'0',"InvalidThursday"=>'0',"InvalidFriday"=>'0',
        "InvalidSaturday"=>'0',"InvalidSunday"=>'0')
    logger.info "the paaramsmsmsms"
    logger.info res.inspect
    logger.info res.to_hash
  end
  
  
  def self.get_rates(params)
     uri = URI('http://test.reconline.com/recoupdate/update.asmx/GetRates')
     res = Net::HTTP.post_form(uri,'User'=>'kedar', 'Password'=>'ked2012','idHotel'=>'38534','idSystem'=>'0','ForeignPropCode'=>'blank','IncludeRateLevels'=>'BAR','ExcludeRateLevels'=>'','IncludeRoomTypes'=>params[:room_type]  ,'ExcludeRoomTypes'=>'','RateType'=>'1','StartDate'=>params[:start_date] ,'EndDate'=> params[:end_date] )
     logger.info "the paaramsmsmsms"
    logger.info res.inspect
    logger.info res.to_hash
    logger.info res.body.include?("<boolean xmlns=\"http://www.reconline.com/\">true</boolean>")
    logger.info res.body
    logger.info res.to_hash
    if !params[:room_type].blank?
       res = XmlSimple.xml_in(res.body)
    end
    logger.info res
    logger.info "ressssssssssssssssssss"
    res 
  end

  
  def self.update_rates(params)
     uri = URI('http://test.reconline.com/recoupdate/update.asmx/UpdateRates')
   res = Net::HTTP.post_form(uri, 'User'=>params[:User],'Password'=>params[:Password],
  "idHotel"=> params[:idHotel] ,"idSystem"=>params[:idSystem],"ForeignPropCode"=>params[:ForeignPropCode],
        "IncludeRateLevels"=>params[:IncludeRateLevels],"ExcludeRateLevels"=> params[:ExcludeRateLevels],
        "IncludeRoomTypes"=>params[:IncludeRoomTypes],"ExcludeRoomTypes"=>params[:ExcludeRoomTypes],"RateType"=>
          params[:RateType],
        "StartDate"=> params[:StartDate],"EndDate"=>params[:EndDate],"SingleOcc"=>params[:SingleOcc],"DoubleOcc"=>params[:DoubleOcc],
        "TripleOcc"=>params[:TripleOcc],"DoublePlusChild"=>params[:DoublePlusChild],
        "RollawayAdult"=>params[:RollawayAdult],"RollawayChild"=>params[:RollawayChild],"Crib"=>params[:Crib],"Meals"=>params[:Meals],
        "Advance"=> params[:Advance],"MinStay"=> params[:MinStay],
        "BlockStay"=> params[:BlockStay],"Guarantee"=>params[:Guarantee],"Cancel"=>params[:Cancel],"CTAMonday"=>params[:CTAMonday],
        "CTATuesday"=>params[:CTATuesday] ,
        "CTAWednesday"=>params[:CTAWednesday],"CTAThursday"=>params[:CTAThursday],"CTAFriday"=>params[:CTAFriday],"CTASaturday"=>params[:CTASaturday],
        "CTASunday"=>params[:CTASunday],
        "InvalidMonday"=>params[:InvalidMonday],"InvalidTuesday"=>params[:InvalidTuesday],"InvalidWednesday"=>params[:InvalidWednesday],"InvalidThursday"=>params[:InvalidThursday],"InvalidFriday"=>params[:InvalidFriday],
        "InvalidSaturday"=>params[:InvalidSaturday],"InvalidSunday"=>params[:InvalidSunday])
    logger.info "the paaramsmsmsms"
    logger.info res.inspect
    logger.info res.to_hash
    logger.info res.body.include?("<boolean xmlns=\"http://www.reconline.com/\">true</boolean>")
    logger.info res.body
    logger.info res.to_hash
    res 
  end
  
  
end

app/controllers/updateretes_controller.rb
class UpdateretesController < ApplicationController
  # GET /updateretes
  # GET /updateretes.json
  
   layout 'gds'
   before_filter :check_gds_availability
  def index
   # @updateretes = Updaterete.update_rates

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @updateretes }
    end
  end
  
  #before getting an new rates i need to update that single rate through web service
  def update_rates
   
    Updaterete.update_single_rate(params)
    @get_rates = Updaterete.get_rates(params)
    render :layout=>"gds"
  end
  

  #this will fetch all the rates availability and just parse and show it in view
  def show_rates
   
    @get_rates = Updaterete.get_rates(params)
    render :layout=>"gds"
  end
  
  
  # GET /updateretes/1
  # GET /updateretes/1.json
  def show
    @updaterete = Updaterete.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @updaterete }
    end
  end

  # GET /updateretes/new
  # GET /updateretes/new.json
  def new
   # @updaterete = Updaterete.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @updaterete }
    end
  end

  # GET /updateretes/1/edit
  def edit
    @updaterete = Updaterete.find(params[:id])
  end

  # POST /updateretes
  # POST /updateretes.json
  def create
    @updaterete = Updaterete.update_rates(params)
    respond_to do |format|
        if @updaterete.body.include?("<boolean xmlns=\"http://www.reconline.com/\">true</boolean>")
           flash[:notice] = 'Getrate was successfully created.'
           format.html { render :text=>"The Rates Were Properly Updated"  }
           format.json { render json: @updaterete, status: :created, location: @updaterete }
        else
           flash[:notice] = getrate.body
           format.html { render action: "new" }
           format.json { render json: @updaterete.errors, status: :unprocessable_entity }
        end
     end
  end

  # PUT /updateretes/1
  # PUT /updateretes/1.json
  def update
    @updaterete = Updaterete.find(params[:id])

    respond_to do |format|
      if @updaterete.update_attributes(params[:updaterete])
        format.html { redirect_to @updaterete, notice: 'Updaterete was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @updaterete.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /updateretes/1
  # DELETE /updateretes/1.json
  def destroy
    @updaterete = Updaterete.find(params[:id])
    @updaterete.destroy

    respond_to do |format|
      format.html { redirect_to updateretes_url }
      format.json { head :no_content }
    end
  end
   private
  def check_gds_availability
    begin
      logger.info GDS
    rescue
      redirect_to gds_auths_path ,:notice=>"Your Session Has Been Expired Please Login Again" and return
    end
    #here i also need to check an session for gusername is available or not for logged in user purpose.
     if session[:gusername].blank?
        redirect_to gds_auths_path,:notice=>"Your Session Has Been Expired Please Login Again" and return
     end
    
    
  end
end

app/helpers/updateretes_helper.rb
module UpdateretesHelper
end

app/views/updateretes/edit.html.erb
<h1>Editing updaterete</h1>

<%= render 'form' %>

<%= link_to 'Show', @updaterete %> |
<%= link_to 'Back', updateretes_path %>

app/views/updateretes/index.html.erb
<h1>Listing updateretes</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

 
</table>

<br />

<%= link_to 'New Updaterete', new_updaterete_path %>

app/views/updateretes/new.html.erb
<h1>New Update Rate</h1>

<%= render 'form' %>

 

app/views/updateretes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_updaterete_path(@updaterete) %> |
<%= link_to 'Back', updateretes_path %>

app/views/updateretes/show_rates.html.erb
<%=form_tag updateretes_show_rates_path%>
<div class="">

<div class="todate_fromdatebg">
<div class="todate_fromdateheadingbg">
<table><tr><td>
 <%= link_to 'Back', getbookings_path ,:class=>"submit_button"%>
  </td>
  </tr>
  </table>
</div>
  <table align="center">
    <tr>
  <td class="todate_fromdateheadingtext">
  Select Type
 </td>
 <td>
   <%if params[:room_type] == "DBL"%>
        <%=select_tag "room_type", "<option value='DBL' selected='selected'>DBL</option><option value='KING'>KING</option>".html_safe%>

   <%elsif params[:room_type] == "KING"%>
        <%=select_tag "room_type", "<option value='DBL' >DBL</option><option value='KING' selected='selected'>KING</option>".html_safe%>
   <%else%>
        <%=select_tag "room_type", "<option value='DBL' >DBL</option><option value='KING'>KING</option>".html_safe%>
   
   <%end%>
   
   </td>
 </tr>
 <tr>
   <td class="todate_fromdateheadingtext">
     Start Date
   </td>
  
  <td>
<%=text_field_tag "start_date"  %>
</td>
</tr>

 <tr>
   <td class="todate_fromdateheadingtext">
    End Date
   </td>
   <td>
<%=text_field_tag "end_date"  %>
</td>
</tr>
 </table>
  <table align="center">
<tr>
  
    <td>
     
      
    <%=submit_tag "Submit",:class=>"submit_button4"%>
       
         
    </td></tr>
</table>
 

</form>

</div>
<div class="" id="todate_fromdatebg1" style="display:none">
<%=form_tag updateretes_update_rates_path ,:onsubmit=>"$('#todate_fromdatebg1').hide();" %>
<div class="todate_fromdatebg">
<div class="todate_fromdateheadingbg">
     
  
</div>

<table width="352" height="181" border="0" style="margin-left:30px; margin-top:20px; float:left;" >
  <tr span class="todate_fromdateheadingtext">
    <td width="112"><div align="left">Begin Period</div></td>
    <td width="159"><form id="form16" name="form16" method="post" action="">
      <label>
        <%=text_field_tag "begin_period","",:readonly=>true  %>
        </label>
    </form>
    </td>
  </tr>
  <tr span class="todate_fromdateheadingtext">
    <td><div align="left">End Period</div></td>
    <td>
      
       <%=text_field_tag "end_period" ,"",:readonly=>true %>
     <%=hidden_field_tag "start_date" , params[:start_date] %>
     <%=hidden_field_tag "end_date" , params[:end_date] %>
     <%=hidden_field_tag "room_type" , params[:room_type] %>
     
    </td>
  </tr>
  <tr span class="todate_fromdateheadingtext">
    <td><div align="left">I&nbsp; Occ</div></td>
    <td><%=text_field_tag "SINGLEOCCUPANCY"  %></td>
  </tr>
 <tr span class="todate_fromdateheadingtext">
    <td><div align="left">II&nbsp; Occ</div></td>
    <td><%=text_field_tag "DOUBLEOCCUPANCY"  %></td>
  </tr>
  <tr span class="todate_fromdateheadingtext">
    <td><div align="left">III&nbsp; Occ</div></td>
    <td><%=text_field_tag "TRIPLEOCCUPANCY"  %></td>
  </tr>
  <tr span class="todate_fromdateheadingtext">
    <td><div align="left">II + Child</div></td>
    <td><%=text_field_tag "QUADRUPLEOCCUPANCY"  %></td>
  </tr>
  <tr span class="todate_fromdateheadingtext">
    <td><div align="left">+ Adult</div></td>
    <td>  <%=text_field_tag "ROLLAWAYADULT"  %></td>
  </tr>
  <tr span class="todate_fromdateheadingtext">
    <td><div align="left">+ Child</div></td>
    <td><%=text_field_tag "ROLLAWAYCHILD"  %></td>
  </tr>
</table>

<table width="418" height="86" border="0" style="margin-left:30px; float:left; margin-top:15px;" >
  <tr >
    <td height="23" colspan="7" class="selectroomtype"><div align="left">Room Checking</div></td>
  </tr>
  <tr>
    <td width="62"  class="todate_fromdaterequlartext" height="23">Mon    
        <%=check_box_tag  "CTAMO", 0%></td>
    <td width="53" class="todate_fromdaterequlartext">Tu
     <%=check_box_tag  "CTATU", 0%></td>
    <td width="56"  class="todate_fromdaterequlartext">We    
   <%=check_box_tag  "CTAWE", 0%></td>
    <td width="52"  class="todate_fromdaterequlartext">Th
   <%=check_box_tag  "CTATH", 0%></td>
    <td width="44"  class="todate_fromdaterequlartext">Fr
           <%=check_box_tag  "CTAFR", 0%></td>
    <td width="50"  class="todate_fromdaterequlartext">Sat
      <input type="checkbox" name="checkbox13" id="checkbox13" /></td>
    <td width="55"  class="todate_fromdaterequlartext">Sa
       <%=check_box_tag  "CTASA", 0%></td>
  </tr>
  <tr>
    <td height="27">&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td colspan="4" align="right">
      <div class="addroombutton">
         <%=submit_tag "Submit",:class=>"submit_button"%>
      </div> 
    </td>
    
  </tr>
</table>

 
  </form>

</div>

   





</div>

 <%if ((@get_rates !=nil) &&   (!@get_rates.blank?) && (!@get_rates["diffgram"].blank? ) )%>   
<table width="884" height="111" border="1" align="center"  style="border-collapse: collapse;float: left;margin-left: 40px;margin-top: 30px;table-layout: fixed;">
  <tr span class="todate_fromdateheadingtext">
    <td width="36" rowspan="2">Edit</td>
    <td width="74" rowspan="2">Room Type</td>
    <td width="78" rowspan="2">Start Date</td>
    <td width="78" rowspan="2">End Date</td>
    <td width="47" rowspan="2">I Occ</td>
    <td width="51" rowspan="2">II Occ</td>
    <td width="52" rowspan="2">III Occ</td>
    <td width="65" rowspan="2">II+Child</td>
    <td width="55" rowspan="2">+ Adult</td>
    <td width="55" rowspan="2">+ Child</td>
    <td colspan="7"><div align="center">Room Categories</div></td>
  </tr>
 <tr span class="todate_fromdateheadingtext">
    <td width="36">Sun</td>
    <td width="36">Mon</td>
    <td width="35">Tue</td>
    <td width="37">Wed</td>
    <td width="35">Thu</td>
    <td width="36">Fri</td>
    <td width="35">Sat</td>
  </tr>
    <%countperiod = 1%>
    <%if ((@get_rates !=nil) &&   (!@get_rates.blank?) && (!@get_rates["diffgram"].blank? ) )%>
    <%@get_rates["diffgram"][0]["NewDataSet"][0]["Rate"].each do |get_rate|%>
    <%countperiod = countperiod + 1 %>
    <input type="hidden" value="<%=get_rate['BEGINPERIOD'][0].to_s.split('T')[0]%>" id="<%=countperiod%>BEGINPERIOD" />
    <input type="hidden" value="<%=get_rate['ENDPERIOD'][0].to_s.split('T')[0]%>" id="<%=countperiod%>ENDPERIOD" />
    <input type="hidden" value="<%=get_rate['SINGLEOCCUPANCY'][0]%>" id="<%=countperiod%>SINGLEOCCUPANCY" />
    <input type="hidden" value="<%=get_rate['DOUBLEOCCUPANCY'][0]%>" id="<%=countperiod%>DOUBLEOCCUPANCY" />
    <input type="hidden" value="<%=get_rate['TRIPLEOCCUPANCY'][0]%>" id="<%=countperiod%>TRIPLEOCCUPANCY" />
    <input type="hidden" value="<%=get_rate['QUADRUPLEOCCUPANCY'][0]%>" id="<%=countperiod%>QUADRUPLEOCCUPANCY" />
    <input type="hidden" value="<%=get_rate['ROLLAWAYADULT'][0]%>" id="<%=countperiod%>ROLLAWAYADULT" />
    <input type="hidden" value="<%=get_rate['ROLLAWAYCHILD'][0]%>" id="<%=countperiod%>ROLLAWAYCHILD" />
    <input type="hidden" value="<%=get_rate['CTAMO'][0]%>" id="<%=countperiod%>CTAMO" />
    <input type="hidden" value="<%=get_rate['CTATU'][0]%>" id="<%=countperiod%>CTATU" />
    <input type="hidden" value="<%=get_rate['CTAWE'][0]%>" id="<%=countperiod%>CTAWE" />
    <input type="hidden" value="<%=get_rate['CTATH'][0]%>" id="<%=countperiod%>CTATH" />
    <input type="hidden" value="<%=get_rate['CTAFR'][0]%>" id="<%=countperiod%>CTAFR" />
    <input type="hidden" value="<%=get_rate['CTASA'][0]%>" id="<%=countperiod%>CTASA" />
    <input type="hidden" value="<%=get_rate['CTASU'][0]%>" id="<%=countperiod%>CTASU" />
     
    
    <script>
   function update_values(count)
   {
     $('#begin_period').val($('#'+count+'BEGINPERIOD').val());
     $('#end_period').val($('#'+count+'ENDPERIOD').val());
     $('#SINGLEOCCUPANCY').val($('#'+count+'SINGLEOCCUPANCY').val());
     $('#DOUBLEOCCUPANCY').val($('#'+count+'DOUBLEOCCUPANCY').val());
     $('#TRIPLEOCCUPANCY').val($('#'+count+'TRIPLEOCCUPANCY').val());
     $('#QUADRUPLEOCCUPANCY').val($('#'+count+'QUADRUPLEOCCUPANCY').val());
     $('#ROLLAWAYADULT').val($('#'+count+'ROLLAWAYADULT').val());
     $('#ROLLAWAYCHILD').val($('#'+count+'ROLLAWAYCHILD').val());
     
     if ($('#'+count+'CTAMO').val() == 1)
       {
         $("#CTAMO").prop('checked',true);
       }
     if ($('#'+count+'CTATU').val() == 1)
       {
         $("#CTATU").prop('checked',true);
       }
     if ($('#'+count+'CTAWE').val() == 1)
       {
         $("#CTAWE").prop('checked',true);
       }
     if ($('#'+count+'CTATH').val() == 1)
       {
         $("#CTATH").prop('checked',true);
       }
     if ($('#'+count+'CTAFR').val() == 1)
       {
         $("#CTAFR").prop('checked',true);
       }
     if ($('#'+count+'CTASA').val() == 1)
       {
         $("#CTASA").prop('checked',true);
       }
     if ($('#'+count+'CTASU').val() == 1)
       {
         $("#CTASU").prop('checked',true);
       }      
       
      
      
    
      
     $("#todate_fromdatebg1").show();
     
     return false;
     
   }
   </script>
   <tr span class="todate_fromdaterequlartext">
    <td><%=link_to  image_tag("pencil.jpg",:size=>"20x20") ,"#",:onclick=>"return update_values(#{countperiod})"%></td>
    <td> <%=params[:room_type]%></td>
    <td > <%=get_rate['BEGINPERIOD'][0].to_s.split('T')[0]%></td>
    <td > <%=get_rate['ENDPERIOD'][0].to_s.split('T')[0]%></td>
    <td> <%=get_rate['SINGLEOCCUPANCY'][0]%></td>
    <td> <%=get_rate['DOUBLEOCCUPANCY'][0]%></td>
    <td> <%=get_rate['TRIPLEOCCUPANCY'][0]%></td>
    <td> <%=get_rate['QUADRUPLEOCCUPANCY'][0]%></td>
    <td> <%=get_rate['ROLLAWAYADULT'][0]%></td>
    <td><%=get_rate['ROLLAWAYCHILD'][0]%></td>
    <td> <%if get_rate['CTASU'][0] == "1"%>
                <%=check_box_tag "readonlyCTASU" ,"1",true ,:disabled=>true%>
           <%else%>
                <%=check_box_tag "readonlyCTASU" ,"1",false,:disabled=>true %>
           <%end%>
</td>
    <td>             <%if get_rate['CTAMO'][0] == "1"%>
                <%=check_box_tag "readonlyCTAMO" ,"1",true ,:disabled=>true%>
           <%else%>
                <%=check_box_tag "readonlyCTAMO" ,"1",false,:disabled=>true %>
           <%end%>
</td>
    <td>             <%if get_rate['CTATU'][0] == "1"%>
                <%=check_box_tag "readonlyCTATU" ,"1",true ,:disabled=>true%>
           <%else%>
                <%=check_box_tag "readonlyCTATU" ,"1",false,:disabled=>true %>
           <%end%>
</td>
    <td>             <%if get_rate['CTAWE'][0] == "1"%>
                <%=check_box_tag "readonlyCTAWE" ,"1",true ,:disabled=>true%>
           <%else%>
                <%=check_box_tag "readonlyCTAWE" ,"1",false,:disabled=>true %>
           <%end%>
</td>
    <td>             <%if get_rate['CTATH'][0] == "1"%>
                <%=check_box_tag "readonlyCTATH" ,"1",true ,:disabled=>true%>
           <%else%>
                <%=check_box_tag "readonlyCTATH" ,"1",false,:disabled=>true %>
           <%end%>
</td>
    <td>          <%if get_rate['CTAFR'][0] == "1"%>
                <%=check_box_tag "readonlyCTAFR" ,"1",true ,:disabled=>true%>
           <%else%>
                <%=check_box_tag "readonlyCTAFR" ,"1",false,:disabled=>true %>
           <%end%>
</td>
    <td>             <%if get_rate['CTASA'][0] == "1"%>
                <%=check_box_tag "readonlyCTASA" ,"1",true ,:disabled=>true%>
           <%else%>
                <%=check_box_tag "readonlyCTASA" ,"1",false,:disabled=>true %>
           <%end%>
</td>
    
    
   
   
   <%end%>
   <%end%>
  
  
</table>
 <%end%>
  
  
  </div>