config/routes.rb
HotelMgtWithWorkflowChanged::Application.routes.draw do
  
  

  
  post  "room_books/action_gds_conf"
  
  post "room_books/add_room"
  get  "room_books/add_room"
  post  "room_books/view_rooms"
  
  
  
  post "room_books/add_room_date"
  get "room_books/add_room_date"
  post "room_books/index_with_pag"
  
  
  get "room_books/add_room_date"
  
  
  post 'room_books/get_available_room_type'
  get 'room_books/get_available_room_type'
  
  post 'room_books/add_to_gds'
  
  post 'room_books/delete_gdsline'
  
  get 'room_books/show_type/:id' => "room_books#show_type"
  post "room_books/available_for_gds" => "room_books#available_for_gds"
  post "room_books/available_for_gds/:id" => "room_books#available_for_gds"
  
  get "room_books/available_for_gds/:id" => "room_books#available_for_gds"
  get "room_books/edit_available_for_gds/:id" => "room_books#edit_available_for_gds"
  
  post "room_books/delete_allocated_room" => "room_books#delete_allocated_room"
  get "room_books/add_an_item"
  post "room_books/add_an_item"
  
  get "room_books/show_view/:id" => "room_books#show_view"
  
  get "room_books/select_shop"
  
  
  
  resources :room_books

  post "reservations/show_dates"
  get  "reservations/show_dates"
  post "reservations/show_availability_of_rooms"
  get  "reservations/room_confirm/:id" => "reservations#room_confirm"
  post  "reservations/room_confirm/" => "reservations#room_confirm"
  
  
  
  resources :reservations
  
  get "payments/get_transaction_details"
  post "payments/get_transaction_details"
  
  
  get "payments/preview_payment"
  get "payments/server_connection_error"
  post "payments/checkout"
  get "payments/confirm"
  get "payments/cancel"
  post "payments/complete"
  get "payments/rejected_payment"
  resources :payments
  
   
  
  
   
  root :to => "authenticates#select_company"
  post "authenticates/sign_in"
  get  "authenticates/sign_in"
  get  "authenticates/sign_up"
  post "authenticates/sign_up"
  post "authenticates/sign_in_auth"
  post "/authenticates/sign_up_auth"
  get "/authenticates/forgot_password"
  post "/authenticates/forgot_password_auth"
  get "/authenticates/sign_out"
  
    
  
  resources :authenticates

  
  
  
  resources :admins

  
  get "updateretes/show_rates"
  post "updateretes/show_rates"
  post "updateretes/update_rates"
  
  
  
  
  resources :updateretes

  resources :updatehoteltexts

  resources :updatebookings
  get "updateavails/all_list"
  get "updateavails/show_type/:id" => "updateavails#show_type"
  post "updateavails/available_for_gds/" => "updateavails#available_for_gds"
  post "delete_allocated_room" => "updateavails#delete_allocated_room"
  get "updateavails/get_dates" => "updateavails#get_dates"
  post "get_date_wise_available_room" => "updateavails#get_date_wise_available_room"
  post "add_to_gds" => "updateavails#add_to_gds"
  
  get "count_rooms" => "updateavails#count_rooms"
  get "update_count_rooms" => "updateavails#update_count_rooms"
  
  
  
  
  resources :updateavails

  resources :setmarkassents

  resources :setds

  resources :getroomratecodefbs

  resources :getroomratecodes

  resources :getratesdbs

  resources :getrates

  resources :getnotificationmessages

  resources :getinvoicedata

  resources :gethotels

  resources :gethotelstaticdatagds

  resources :gethotelstaticdata

  resources :getcommissionstatuses

  resources :getbookings

  resources :getavailfbs

  resources :cancelbookings

  resources :bookings

  get "savontest/index"
  
  get "gds_auth" => "gds_auths#index"
  
  get "gds_select_company" => "gds_auths#gds_select_company"
  
  get "logout" => "gds_auths#logout"
  
      
  resources :gds_auths

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
   include ActiveMerchant::Billing
   require 'net/http'
   layout 'web_layout'
    before_filter :check_connection
  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @payments }
    end
  end

  def convert_currency(from_curr = "INR", to_curr = "USD", amount = 1000)
    host = "www.google.com"
    http = Net::HTTP.new(host, 80)
    url = "/finance/converter?a=#{amount}&from=#{from_curr}&to=#{to_curr}"
    response = http.get(url)
    # puts response.body
    result = response.body
    regexp = Regexp.new("(\\d+\\.{0,1}\\d*)\\s+#{to_curr}")
    regexp.match result
    return $1.to_f
 end
 

  
  # GET /payments/1
  # GET /payments/1.json
  def show
    @payment = Payment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @payment }
    end
  end

  # GET /payments/new
  # GET /payments/new.json
  def new
    @payment = Payment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @payment }
    end
  end

  # GET /payments/1/edit
  def edit
    @payment = Payment.find(params[:id])
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(params[:payment])

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render json: @payment, status: :created, location: @payment }
      else
        format.html { render action: "new" }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /payments/1
  # PUT /payments/1.json
  def update
    @payment = Payment.find(params[:id])

    respond_to do |format|
      if @payment.update_attributes(params[:payment])
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment = Payment.find(params[:id])
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url }
      format.json { head :no_content }
    end
  end
  
  #this page is same as 4000 page of paypal. so here i am putting all the code which is same as in my last controller
  #room type. now here i need to cp[y the code just for the purpose of creating an amount.so just check line by line.
  #here in preview what i need to show is user name and checkin and checkout and price and room names
  
  def preview_payment
    #just check an dates
    #check dummy
        @roombarname = []
        @respartner = ResPartner.find(session[:user_id_avail])
        @resname = @respartner.name
        checkindate = DateTime.new(session[:checkin].split(' ')[0].to_s.split('/')[2].to_i,session[:checkin].split(' ')[0].to_s.split('/')[0].to_i,session[:checkin].split(' ')[0].to_s.split('/')[1].to_i,session[:checkin].split(' ')[1].to_s.split(':')[0].to_i,session[:checkin].split(' ')[1].to_s.split(':')[1].to_i )
        checkoutdate = DateTime.new(session[:checkout].split(' ')[0].to_s.split('/')[2].to_i,session[:checkout].split(' ')[0].to_s.split('/')[0].to_i,session[:checkout].split(' ')[0].to_s.split('/')[1].to_i,session[:checkout].split(' ')[1].to_s.split(':')[0].to_i,session[:checkout].split(' ')[1].to_s.split(':')[1].to_i )
         session[:amount] = nil
        if session[:checkin].blank?
          redirect_to root_url ,:notice=>'Your Session Is Expired Please Select Room Again' and return;
        end
           if session["selectedroom"]
           session["selectedroom"].each do |roomid|
            pr =  ProductProduct.find(roomid[0].to_i)
            @roombarname << pr.name
           price = pr.product_tmpl_id.list_price.to_f
              cknp = CheckoutConfiguration.find(:all,:domain=>[['shop_id','=',1]]).first.name
           if cknp == "24hour"
             #here i am copying checkin and checkout variables so that it will not make any conflict in its current flow
             checkindfortd = checkindate
             checkoutdfortd = checkoutdate
             while checkindfortd < checkoutdfortd
                 session[:amount] = session[:amount].to_i + price.to_i
                 checkindfortd = checkindfortd.next_day
            end
            else
             if ((checkoutdate - checkindate).to_i == 0)
                   session[:amount] = session[:amount].to_i + price.to_i
              else
                session[:amount] = session[:amount].to_i + (price.to_i * (checkoutdate - checkindate).to_i )
                end
             end
            end
        end
        @currencyname = "USD"
        if ResCurrency.find(:all,:domain=>[['base','=',true]])[0]
          @currencyname = ResCurrency.find(:all,:domain=>[['base','=',true]])[0].name
        end
         available_paypal_array = ["AUD","CAD","CZK","DKK","EUR","HKD","HUF","JPY","NOK","NZD","PLN","GBP","SGD","SEK","CHF"]
         if available_paypal_array.include?(@currencyname)
         elsif @currencyname == "USD"
         else
             usdr = ResCurrency.find(:all,:domain=>[['name','=','USD' ]])[0]
            @convert_amount = session[:amount].to_i * usdr.rate
         end
    end
   
   
  
   
  
  def checkout
    begin
    available_paypal_array = ["AUD","CAD","CZK","DKK","EUR","HKD","HUF","JPY","NOK","NZD","PLN","GBP","SGD","SEK","CHF"]
    paypal_currency = "USD"
    base_currency = ResCurrency.find(:all,:domain=>[['base','=',true]])[0]
    paypal_amount = params[:amount].to_i
   @multiplybyusrates = false
   if base_currency && available_paypal_array.include?(base_currency.name)
       paypal_currency = base_currency.name
       paypal_amount = params[:amount].to_i * 100
    else
      if base_currency && base_currency.name == "USD"
       paypal_amount = paypal_amount * 100#usd
     else
        if base_currency
         @multiplybyusrates = true
         paypal_amount = (paypal_amount * ResCurrency.find(:all,:domain=>[['name','=', 'USD']])[0].rate)*100
       else
         paypal_amount = paypal_amount * 100
       end
     end
   end
    room_name = []
    @item_hash_array = []
    checkout_hotel_reservation
    setup_response = gateway.setup_purchase(paypal_amount,
    :items => @item_hash_array,
    :ip => request.remote_ip,
    :return_url => url_for(:action => 'confirm', :only_path => false),
    :cancel_return_url => url_for(:action => 'cancel', :only_path => false),
    :currency => paypal_currency
    )
   session[:amount] = params[:amount]
   session[:database_name] = session[:database_name]
   Ipbasesdb.create(:dbname=>"hotel_kedar_1" ,:ipaddress=>setup_response.token)
    redirect_to gateway.redirect_url_for(setup_response.token)
    rescue =>e
       @my_logger ||= Logger.new("#{Rails.root}/log/onlygdsandweb.log")
         logger.info "there is problem in connection"
         logger.info e
         logger.info e.message
         logger.info e.inspect
         @my_logger.info "this is new error"
         @my_logger.info Time.now
         @my_logger.info e.message
         @my_logger.info e.inspect
        redirect_to root_url ,:notice=>"Error in network connection"
    end
  end
    
    
    
    #this code i am keeping as it is because there is no need to hide anything
     def call_create_saleorder_and_invoice(hotelres)
      hotelres.call("confirmed_reservation",[hotelres.id])
      acm = eval(session[:database_name].to_s.upcase.to_s)::AccountMove.new
      acm.journal_id = eval(session[:database_name].to_s.upcase.to_s)::AccountJournal.search([['type','=','bank']])[0]
      acm.company_id = hotelres.company_id.id
      acm.ref = hotelres.reservation_no
      acm.save
      acm.reload
      acml = eval(session[:database_name].to_s.upcase.to_s)::AccountMoveLine.new
      acml.move_id = acm.id
      acml.name = hotelres.reservation_no
      acml.partner_id = hotelres.partner_id.id
      acml.account_id = hotelres.partner_id.property_account_receivable.id
      acml.credit = hotelres.total_cost1
      acml.debit = 0
      acml.status = 'draft'
      base_currency = ResCurrency.find(:all,:domain=>[['base','=',true]])[0]
      available_paypal_array = ["AUD","CAD","CZK","DKK","EUR","HKD","HUF","JPY","NOK","NZD","PLN","GBP","SGD","SEK","CHF"]
      if base_currency
         acml.currency_id = base_currency.id
         if available_paypal_array.include?(base_currency.name)
             acml.amount_currency = "-"+(hotelres.total_cost1).to_s
        elsif base_currency.name == "USD"
             acml.amount_currency = "-"+(hotelres.total_cost1).to_s
        else
                 convertrateusd = ResCurrency.find(:all,:domain=>[['name','=','USD' ]])[0]
                 acml.currency_id = convertrateusd.id
                 acml.amount_currency = "-"+(hotelres.total_cost1 * convertrateusd.rate).to_s
        end
     else
      convertrateusd = ResCurrency.find(:all,:domain=>[['name','=','USD' ]])[0]
      acml.currency_id = convertrateusd.id
      acml.amount_currency = "-"+(hotelres.total_cost1 ).to_s
     end
     acml.save
     acml = eval(session[:database_name].to_s.upcase.to_s)::AccountMoveLine.new
     acml.move_id = acm.id
     acml.name = hotelres.reservation_no
     acml.partner_id = hotelres.partner_id.id
     acml.account_id = eval(session[:database_name].to_s.upcase.to_s)::AccountJournal.find(eval(session[:database_name].to_s.upcase.to_s)::AccountJournal.search([['type','=','bank']])[0]).default_debit_account_id.id
     acml.debit = hotelres.total_cost1
     acml.credit = 0
      if base_currency
         acml.currency_id = base_currency.id
          if available_paypal_array.include?(base_currency.name)

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payments/cancel.html.erb
 <html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Hotel Reservation</title>
<%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
 	 
</head>
<body>	
	<div id="main" style="background-color: #FFFFFF">
<h1>Cancelled  Payment Details</h1>

 
 </div>
</body>
</html>

app/views/payments/complete.html.erb
<div class="welcome1">
      <%=link_to "Check Room",root_path%>
</div>
<div class="signup_bg_compl">

<div class="">

<div class="signuptext">Your Reservation Is Successfull and Your Reservation Id is <%=@reservation_no%> 
  <br/>
  <br/>
  <span class="signuptextcolor"> Thanks</span> </div>
</div>
  </div>


 

app/views/payments/confirm.html.erb
 <div class="signup_bg">

<div class=" signupheadingbg">

<div class="signuptext">Payment<span class="signuptextcolor"> Preview</span> </div>
</div>
<table width="200" border="0" align="center">
  <tr>
    <td width="138" height="49"><span class="listening_eventstext"> Name :</span></td>
    <td width="283"><span class="listening_eventstext"><%= @address['name'] %></span></td>
  </tr>
  
  <tr>
    <td height="41"><span class="listening_eventstext">Address 1 :</span></td>
    <td class="listening_eventstext"><%= @address['address1'] %></td>
  </tr>
  <tr>
    <td height="47" class="listening_eventstext">Address 2 </td>
    <td class="listening_eventstext"><%= @address['address2'] %></td>
  </tr>
   <tr>
    <td height="45" class="listening_eventstext">City</td>
    <td class="listening_eventstext"><%= @address['city'] %></td>
  </tr>
   <tr>
    <td height="45" class="listening_eventstext">State</td>
    <td class="listening_eventstext"><%= @address['state'] %></td>
  </tr>
   <tr>
    <td height="45" class="listening_eventstext">Country</td>
    <td class="listening_eventstext"><%= @address['country'] %></td>
  </tr>  
  
  <tr>
    <td height="45" class="listening_eventstext">Zip</td>
    <td class="listening_eventstext"><%= @address['zip'] %></td>
  </tr>
  <tr>
    <td height="45" class="listening_eventstext">Amount</td>
    <td class="listening_eventstext"><%= session[:amount] %></td>
  </tr>
    <%if !@convert_amount.blank?%>
  <tr>
    <td height="45" class="listening_eventstext">USD Conversion </td>
    <td class="listening_eventstext"> 
    <%=@convert_amount%>&nbsp;&nbsp;&nbsp;&nbsp;<%="USD" %>
    </td>
 <!-- this is for adding just a new comment in github -->
  </tr>
  <%end%>
  <tr>
    <td height="45" class="listening_eventstext">Check In </td>
    <td class="listening_eventstext"><%= session[:checkin] %></td>
  </tr>
  <tr>
    <td height="45" class="listening_eventstext">Check Out </td>
    <td class="listening_eventstext"><%= session[:checkout] %></td>
  </tr>
  <tr>
    <td height="45" class="listening_eventstext">Rooms </td>
    <td class="listening_eventstext"><%= @room.join(",") %></td>
  </tr>
  
  
  
  
  
  <tr>
     
    <td>
      <%= form_tag :action => 'complete', :token => params[:token], :payer_id => params[:PayerID] do %>
      <%= token_tag(nil) %>
      
      <%= submit_tag 'Complete Payment' ,:id=>"Checkavailabilitybutton2"%>
      </td>
      <td>
       <div class="viewbutton">
                <ul>
                <li>
      <%= link_to 'Reject Payment' ,payments_rejected_payment_path({:token=>params[:token]}),:class=>"Checkavailabilitybutton"%>
                  </li>
                  </ul>
         </div>
<% end %>
      
    </td>
  </tr>
   
</table>
 




</div>






 

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/error.html.erb
<div class="welcome">
      <%=link_to "Select Hotel",root_path%>
</div>
<div>
  There Are some Errors While Doint This Transactions as follows
</div>

<div>
   <%=@message%>
</div>

app/views/payments/get_transaction_details.html.erb
 <div style="padding:10px">
   Enter A Transaction Id To Get Details Of Paypal History
   </div>
<div style="padding:10px">
<%=form_tag payments_get_transaction_details_path%>
<%=text_field_tag "transaction_id"%>
  <div style="padding:5px">
<%=submit_tag "Check Details" ,:class=>'Checkavailabilitybutton'%>
    </div>
  </div>
<div style="padding:50px">
  <%=@transactiodetails%>
  </div>
<div>
  <br/><br/><br/>
  <%=@transactiodetailss%>
  </div>

app/views/payments/index.html.erb
<h1>Listing payments</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @payments.each do |payment| %>
  <tr>
    <td><%= link_to 'Show', payment %></td>
    <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
    <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New payment</h1>

<%= render 'form' %>

<%= link_to 'Back', payments_path %>

app/views/payments/preview_payment.html.erb
  <form action="<%=payments_checkout_path%>" method="post">
<div class="signup_bg">

<div class=" signupheadingbg">

<div class="signuptext">Payment<span class="signuptextcolor"> Preview</span> </div>
</div>

            <%= token_tag(nil) %>  
<table width="431" border="0" align="center">
  <tr>
    <td width="138" height="49"><span class="listening_eventstext">Contact Name :</span></td>
    <td width="283"><span class="listening_eventstext"><%=@respartner.name%></span></td>
  </tr>
  <tr>
    <td height="42"><span class="listening_eventstext">Check in Date :</span></td>
    <td class="listening_eventstext"><%=session[:checkin]%></td>
  </tr>
  <tr>
    <td height="41"><span class="listening_eventstext">Check Out Date :</span></td>
    <td class="listening_eventstext"><%=session[:checkout]%></td>
  </tr>
  <tr>
    <td height="47" class="listening_eventstext">Room Name </td>
    <td class="listening_eventstext"><%=@roombarname.join(",")%></td>
  </tr>
   <tr>
    <td height="45" class="listening_eventstext">Amount </td>
    <td class="listening_eventstext"> 
    <%=text_field_tag :amount,session[:amount],:readonly=>true%><%=@currencyname%>
    </td>
 
  </tr>
  <%if !@convert_amount.blank?%>
  <tr>
    <td height="45" class="listening_eventstext">USD Conversion </td>
    <td class="listening_eventstext"> 
    <%=text_field_tag :convertedusd,@convert_amount,:readonly=>true%><%="USD" %>
    </td>
 
  </tr>
  <%end%>
  
  <tr>
    <td height="31">&nbsp; </td>
    <td><%=image_submit_tag("btn_xpressCheckout.gif")%></td>
  </tr>
   
</table>
 
</div>

</form>

app/views/payments/server_connection_error.html.erb
<div class="failure_message">
      Server connection failed. Please contact on : 020 - 41201035
</div>
<div>
  <%=link_to "Select Hotel",root_url %>
</div>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>